//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietMuonTras = new HashSet<ChiTietMuonTra>();
            this.PhanLoaiSaches = new HashSet<PhanLoaiSach>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public int SoLuongTon { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int SoLanMuon { get; set; }
        public string AnhBia { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuonTra> ChiTietMuonTras { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanLoaiSach> PhanLoaiSaches { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
