//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int MaViPham { get; set; }
        public int MaDocGia { get; set; }
        public Nullable<int> MaMuonTra { get; set; }
        public string LoaiViPham { get; set; }
        public System.DateTime NgayViPham { get; set; }
        public string HinhThucPhat { get; set; }
        public string TrangThaiXuLy { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual MuonTra MuonTra { get; set; }
    }
}
