//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMuonTra
    {
        public int MaChiTiet { get; set; }
        public int MaMuonTra { get; set; }
        public int MaSach { get; set; }
        public int SoLuongMuon { get; set; }
        public string GhiChu { get; set; }
        public string TinhTrangKhiTra { get; set; }
    
        public virtual MuonTra MuonTra { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
