//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.TheMuonSaches = new HashSet<TheMuonSach>();
            this.ViPhams = new HashSet<ViPham>();
        }
        [Key] // Dòng 1: Đánh dấu đây là Khóa Chính
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Dòng 2: Báo rằng giá trị được tạo tự động bởi database

        public int MaDocGia { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Lop { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public System.DateTime NgayTaoTaiKhoan { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheMuonSach> TheMuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViPham> ViPhams { get; set; }
    }
}
