//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MuonTra()
        {
            this.ChiTietMuonTras = new HashSet<ChiTietMuonTra>();
            this.ViPhams = new HashSet<ViPham>();
        }
    
        public int MaMuonTra { get; set; }
        public int MaTheMuon { get; set; }
        public int MaThuThu { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayHenTra { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public string TrangThai { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuonTra> ChiTietMuonTras { get; set; }
        public virtual TheMuonSach TheMuonSach { get; set; }
        public virtual ThuThu ThuThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViPham> ViPhams { get; set; }
    }
}
