//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSach
    {
        public int MaSach { get; set; }
        public int MaTheLoai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
