//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheMuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheMuonSach()
        {
            this.MuonTras = new HashSet<MuonTra>();
        }
    
        public int MaTheMuon { get; set; }
        public int MaDocGia { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayKichHoat { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string TinhTrangThe { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuonTra> MuonTras { get; set; }
    }
}
